### ISSUE TITLE
How can i help?

### ISSUE THREAD

**Issue by Bashamega** [Rubiidev-IPad/mii-test#1]

**Comment by rubiidev18alt** [comment]
create the ui based on the reference image, some mii creation capabilities, and a few other stuff, ill tweak it, other users like nms and dumo will help, (this is my alt btw)

**Comment by Bashamega** [comment]
Which tech stack do you want to use?

**Comment by rubiidev18alt** [comment]
MERN, idk why you wanted to say that. you can implement the stack tho

**Comment by rubiidev18alt** [comment]
make it basic so I can tweak

**Comment by Bashamega** [comment]
> MERN, idk why you wanted to say that. you can implement the stack tho

i mean do you want easy html css and js, or next.js  + tailwind + reacti.js, or svelte.

**Comment by rubiidev18alt** [comment]
easy html css js

**Comment by Bashamega** [comment]
> easy html css js

okay
